### ISSUE TITLE
same problem. Windows users Just change or add ncores=1 when running simulate function, it might take time but it works!

### ISSUE THREAD

**Issue by gilljos1** [timchurches/blog#11]
same problem. Windows users Just change or add ncores=1 when running simulate function, it might take time but it works!

_Originally posted by @SandyBy in https://github.com/timchurches/blog/issues/5#issuecomment-605612073_

Same error when I run the following command. How can i fix this? Thank you for helping.

ramp_quar_rate_sim <- simulate(quar.rate = quar_rate_ramp(1:366))
Error in { : task 1 failed - "could not find function "init_status.icm""

**Comment by SandyBy** [comment]
try this! hope it works.
ramp_quar_rate_sim <- simulate(quar.rate = quar_rate_ramp(1:366),ncores=1)

**Comment by SandyBy** [comment]
> same problem. Windows users Just change or add ncores=1 when running simulate function, it might take time but it works!
> 
> _Originally posted by @SandyBy in [#5 (comment)](https://github.com/timchurches/blog/issues/5#issuecomment-605612073)_
> 
> Same error when I run the following command. How can i fix this? Thank you for helping.
> 
> ramp_quar_rate_sim <- simulate(quar.rate = quar_rate_ramp(1:366))
> Error in { : task 1 failed - "could not find function "init_status.icm""

ncores=1

**Comment by XiangBu** [comment]
@gilljos1 
try this! hops it works.
ramp_quar_rate_sim <- simulate(quar.rate = quar_rate_ramp(1:366),ncores=1)

**Comment by gilljos1** [comment]
> @gilljos1
> try this! hops it works.
> ramp_quar_rate_sim <- simulate(quar.rate = quar_rate_ramp(1:366),ncores=1)

It worked! Thanks
